# Generated by Django 5.1.6 on 2025-02-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='titulo',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='conteudo',
            new_name='status',
        ),
    ]
